// types.js
export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
export const RESET_QUIZ = "RESET_QUIZ";
